from webapps.oluwa.models.baseModel import *
from webapps.oluwa.models.contactModel import *
from webapps.oluwa.models.profileModel import *
from webapps.oluwa.models.eventsModel import *
from webapps.oluwa.models.missionModel import *
from webapps.oluwa.models.pressModel import *
from webapps.oluwa.models.intelModel import *
from webapps.oluwa.models.logisticsModel import *
from webapps.oluwa.models.mediaModel import *
from webapps.oluwa.models.newsModel import *
from webapps.oluwa.models.trainingModel import *